pipeline {
    agent any

    environment{
        SVC_ACCOUNT_KEY = credentials('jenkins-pipeline')
    }

    parameters {
        booleanParam(name: 'Apply', defaultValue: false, description: 'Automatically run apply after manual approval?')
        booleanParam(name: 'Destroy', defaultValue: false, description: 'Destroy Terraform build?')
    }

    stages {
        stage('Checkout') {
            steps {
            checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/dallisonlima/jenkins-terragrunt']]])            

          }
        }

        stage('Plan') {
            steps {
                dir('dev/us-east-1/vpc'){
                    sh 'ls -la'
                    sh 'cat ~/.aws/credentials'
                    sh 'terragrunt plan'
                } 
            }
        }

        stage('Approval') {
            steps {
                script {
                    def test = params.Destroy
                    if (test == true) {
                        script {
                            def userInput = input(id: 'Confirm', message: 'Deseja fazer o destroy do terraform?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Destroy terraform', name: 'Confirm'] ])
                        }
                    } else {
                        script {
                            def userInputs = input(id: 'Confirm', message: 'Deseja fazer o Apply do terraform?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Apply terraform', name: 'Confirm'] ])
                        }
                    }
                }
            }
        }

        stage('Apply') {
            when {
                not {
                    equals expected: true, actual: params.Destroy
                }
            }
            
            steps {
                dir('dev/us-east-1/vpc'){
                    sh 'ls -la'
                    sh 'terragrunt apply --auto-approve'
                }
            }
        }
        
        stage('Destroy') {
            when {
                equals expected: true, actual: params.Destroy
            }
        
            steps {
                dir('dev/us-east-1/vpc'){
                        sh 'ls -la'
                        sh 'terragrunt destroy --auto-approve'
                    }
            }
        }
    } 
}
